---
- name: Verify
  hosts: all
  tasks:
    - name: Linux | Glab should be functionnal
      ansible.builtin.command: glab --version
      register: glab_version_result

    - name: Linux | Verify commands outputs
      ansible.builtin.assert:
        that:
          - glab_version_result.rc == 0
        success_msg: "All tests passed"
