---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-glab"
      ansible.builtin.include_role:
        name: "ansible-role-glab"
      vars:
        glab_version: "{{ lookup('env', 'glab_version') | default('latest', true) }}"
