---
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: windows-2k19
    box: peru/windows-server-2019-standard-x64-eval
    memory: 8192
    cpus: 4
provisioner:
  name: ansible
  options:
    extra-vars: "{
      'ansible_become': 'false',
      'ansible_user': 'vagrant',
      'ansible_password': 'vagrant',
      'ansible_port': '5985',
      'ansible_connection': 'winrm',
      'ansible_winrm_transport': 'basic',
      'ansible_winrm_server_cert_validation': 'ignore',
      'ansible_shell_type': 'powershell',
      'ansible_shell_executable': 'None'
    }"
