---
- name: Verify
  hosts: all
  tasks:
    - name: Windows | Glab should be functionnal
      ansible.windows.win_command: glab --version
      register: glab_version_result

    - name: Windows | Verify commands outputs
      assert:
        that:
          - glab_version_result.rc == 0
        success_msg: "All tests passed"
